### ISSUE TITLE
ValueError: Expecting property name enclosed in double quotes: line 655 column 9 (char 25131)

### ISSUE THREAD

**Issue by evandrocoan** [sublimator/EditPreferences#9]
### ValueError: Expecting property name enclosed in double quotes: line 655 column 9 (char 25131)

When opening the:

![image](https://cloud.githubusercontent.com/assets/5332158/20640671/7c863c2c-b3cb-11e6-9ad1-5cec9391a3c7.png)

```
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 797, in run_
    return self.run()
  File "commands_base in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\Edit Preferences.sublime-package", line 58, in run
  File "commands_base in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\Edit Preferences.sublime-package", line 26, in glob_and_parse_package_json
  File "./python3.3/json/__init__.py", line 329, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 367, in raw_decode
  File "jsonix in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\Edit Preferences.sublime-package", line 180, in _scan_once
  File "./python3.3/json/decoder.py", line 197, in JSONObject
  File "jsonix in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\Edit Preferences.sublime-package", line 180, in _scan_once
  File "./python3.3/json/decoder.py", line 197, in JSONObject
  File "jsonix in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\Edit Preferences.sublime-package", line 180, in _scan_once
  File "./python3.3/json/decoder.py", line 219, in JSONObject
ValueError: Expecting property name enclosed in double quotes: line 655 column 9 (char 25131)

```

**Comment by FichteFoll** [comment]
Can you provide a list of your installed packages? Just so I could be sure it is the bug I assume it to be when I allocate some time to this package,

**Comment by evandrocoan** [comment]
Ok. This are all my packages currently installed: 

1. https://github.com/evandrocoan/SublimeTextStudio/blob/develop/User/Package%20Control.sublime-settings

On the list `installed_packages` you will find all installed by package control.
On the list `auto_upgrade_ignore` you will find all installed by `git clone`.
Some packages are unlisted because they are small and just created right on the main repo.

1. https://github.com/evandrocoan/SublimeTextStudio/tree/develop

___
### Off topic

How much would this differ from: https://packagecontrol.io/packages/Preferences%20Editor ?

I forked it on github and fixed some issues and added some features: 

1. https://github.com/evandrocoan/SublimePreferencesEditor

Although, this package seems more power full, is that so?
